document.write('<link href="'+gBaseURL._wsg+'common/codeview/styles/shCoreDefaultWhite.css" rel="stylesheet" />');
document.write('<script src="'+gBaseURL._wsg+'common/js/addon/jquery.mCustomScrollbar.min.js"></script>');
document.write('<script src="'+gBaseURL._wsg+'common/js/addon/jquery.clipboard.min.js"></script>');
document.write('<script src="'+gBaseURL._wsg+'common/js/guide.js"></script>');
document.write('<script src="'+gBaseURL._wsg+'common/codeview/scripts/shCore.js?cb=undefined"></script>');
document.write('<script src="'+gBaseURL._wsg+'common/codeview/scripts/shAutoLoader.js?cb=undefined"></script>');
document.write('<script src="'+gBaseURL._wsg+'common/codeview/scripts/shBrushjScript.js?cb=undefined"></script>');
document.write('<script src="'+gBaseURL._wsg+'common/codeview/scripts/shBrushXml.js?cb=undefined"></script>');
document.write('<script src="'+gBaseURL._wsg+'common/codeview/scripts/shBrushCss.js?cb=undefined"></script>');
document.write('<script>SyntaxHighlighter.all();</script>');